# Generated by Django 3.1.7 on 2021-06-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodssku',
            table='df_goods_sku',
        ),
    ]
